name: Get Commit Message from Event Object

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit message (Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          echo "Commit Title: ${{ github.event.pull_request.title }}"
          echo "Commit Body: ${{ github.event.pull_request.body }}"