name: "Terraform Plan"

on:
  pull_request:
    types:
      - opened
env:
  TF_CLOUD_ORGANIZATION: "vothdev"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "hcp-az-github-workflow-dev"
  CONFIG_DIRECTORY: "./"

jobs:
    run_if:
      if: startsWith(github.head_ref, 'feat/')
      runs-on: ubuntu-latest
      steps:
        - run: echo "The head of this PR starts with 'feat/'"